### ISSUE TITLE
需要更新 API

### ISSUE THREAD

**Issue by shansing** [Tooruchan/simple-forwarder-bot#2]
启动警告：

> main.py:218: TelegramDeprecationWarning: Old Handler API is deprecated - see https://git.io/fxJuV for details
>    updater = Updater(Token)

python-telegram-bot-12.4.2

**Comment by Tooruchan** [comment]
未来这个Bot会切换到以Pyrogram作为主要技术栈的版本

**Comment by insoxin** [comment]
> 未来这个Bot会切换到以Pyrogram作为主要技术栈的版本

你演示挂了吗 这个还能不能用
